version: "3.8"

services:
  app:
    build: .
    container_name: node-todo-app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
 
