name: Docker Compose CI

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: me-south-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2


    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: 679357059961.dkr.ecr.me-south-1.amazonaws.com/node-todo-app:latest

    - name: Deploy on EC2 instance
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 157.175.53.129
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          aws ecr get-login-password --region me-south-1 | docker login --username AWS --password-stdin 679357059961.dkr.ecr.me-south-1.amazonaws.com

          docker pull 679357059961.dkr.ecr.me-south-1.amazonaws.com/node-todo-app:latest

          docker stop todo-app || true
          docker rm todo-app || true

          docker network create app-net || true

          docker run -d \
            --name todo-app \
            --network app-net \
            --env-file .env \
            -p 80:3000 \
            679357059961.dkr.ecr.me-south-1.amazonaws.com/node-todo-app:latest

          docker ps