name: Docker Compose CI

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Create .env file if needed
      run: |
        if [ ! -f .env ]; then
          echo "PORT=3000" >> .env
          echo "MONGODB_URI=mongodb://mongodb:27017/tododb" >> .env
        fi

    - name: Build and Start Docker Compose
      run: |
        docker-compose up -d --build
        sleep 10  # wait for containers to initialize

    - name: Check running containers
      run: docker ps

    - name: Logs (Optional)
      run: docker-compose logs --no-color

    - name: Shut down containers
      if: always()
      run: docker-compose down
